// layout.tsx veya layout.jsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Inter, Roboto } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/ConditionalHeader";

// 1. Font'ları yükle (variable: CSS değişkeni oluşturur)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '300', '400'],
  variable: '--font-inter',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto', 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" data-scroll-behavior="smooth">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${montserrat.variable}
          ${inter.variable}
          ${roboto.variable}
          antialiased
        `}
      >
        <ConditionalHeader />
       
        <main >
          {children}
        </main>

      </body>
    </html>
  );
}